"""add documents

Revision ID: bbcaa3812277
Revises: 444a071fe85e
Create Date: 2026-08-24 20:28:49.832722

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bbcaa3812277'
down_revision: Union[str, Sequence[str], None] = '444a071fe85e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('user_id', sa.INTEGER(), nullable=False))
    # ### end Alembic commands ###
